### ISSUE TITLE
No hyperlinks for @username and #tags

### ISSUE THREAD

**Issue by ravimallya** [tweecool/tweecool-jquery-plugin#1]
for ex: It is displaying like this
Answer on @Quora by Vincen Mathai to Who are the best IAS/IPS officers #India has seen? <a target="_blank" href="http://t.co/7NWexrkIJH">http://t.co/7NWexrkIJH</a> 
1 months ago

Here @username and #hastags needed to be hyperlinked for respective user pages and tags page right? Can we fix it?

You can check it at: http://www.jqueryscript.net/demo/jQuery-Plugin-To-Display-Your-Tweets-On-The-Web-Page-TweeCool/ also.

**Comment by tweecool** [comment]
Well this is not an issue, barely important but we are going to add this to our todo list.

**Comment by tweecool** [comment]
Hyperlinks added. Please use 1.6 version of TweeCool. Thank you.
