### ISSUE TITLE
404 on tweecool api

### ISSUE THREAD

**Issue by polonel** [tweecool/tweecool-jquery-plugin#2]
Getting 404 on the tweecool api:  https://www.api.tweecool.com/?screenname

**Comment by tweecool** [comment]
Back to normal now.
On Sep 18, 2015 02:09, Chris Brame notifications@github.com wrote:Getting 404 on the tweecool api:  https://www.api.tweecool.com/?screenname

**Comment by monstter** [comment]
Hey

Getting 404 on the tweecool api!

Thanks

**Comment by tweecool** [comment]
Hi,
We are looking into this,
Regards
On 21 Oct 2015 17:15, monstter notifications@github.com wrote:Hey

Getting 404 on the tweecool api!

Thanks

**Comment by monstter** [comment]
Any news about the problem?

**Comment by tweecool** [comment]
Hi,
My current server can't cope with the traffic, I have been asked to move to a dedicated server which cost a lot, as you know this is free service, so I don't generate any revenue from this, so I can't afford the cost on my own. Until I find a better server I am afraid this is the end.
Regards.
On 22 Oct 2015 10:10, monstter notifications@github.com wrote:Any news about the problem?

**Comment by skiokko** [comment]
Hi,
Sorry only a confirmation, plugin will never work again right?
I totally understand, its free, im surpised you should use your server, was sure was all by twitter.

Thanks

**Comment by tweecool** [comment]
For the past 3 years, 
The server, domain name, and ssl cost it's been on me. I try to get people to click those ads in order to generate a revenue in order to cover those costs but nobody was interested. Today my web host asked to move to a dedicated server because TweeCool is getting too much traffic so no longer allowed on shared hosting. Dedicated server or vps cost a lot, so I can't pay for it on my own, therefore until I find a free or decent alternative TweeCool will be off. Sorry!
My personal stuff are down as well, so we are all on the boat.

On 22 Oct 2015 10:29, skiokko notifications@github.com wrote:Hi,
Sorry only a confirmation, plugin will never work again right?
I totally understand, its free, im surpised you should use your serve, was sure was all twitter.

Thanks

**Comment by skiokko** [comment]
Thanks for answer! Understood, I also tried years ago a free service but revenue of ADS was zero. Only goodway I found to make money is to publish plugins on http://codecanyon.net/
Good luck.
Federico

**Comment by rdiezv** [comment]
Hi, check this VPS: http://www.servermom.org/boltvm-promo/2490/  ==>
20$/year.
It's better than a shared hosting but not very expensive.

2015-10-22 12:28 GMT+02:00 skiokko notifications@github.com:

> Thanks for answer! Understood, I also tried years ago a free service but
> revenue of ADS was zero. Only goodway I found to make money is to publish
> plugins on http://codecanyon.net/
> Good luck.
> Federico
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tweecool/tweecool-jquery-plugin/issues/2#issuecomment-150173788
> .

## 

_Rafael Díez_
email: rdiezv@gmail.com
twitter: @rdiezv https://twitter.com/rdiezv
web: www.rafaeldiez.com

**Comment by skiokko** [comment]
Seem a very very good price, if there is some guarantee that plugin will comeback online and stay live for about 1y I will be happy to pay 20$ for this hosting.

**Comment by skiokko** [comment]
Some small support to author is nothing for this great plugin.

**Comment by monstter** [comment]
I also support for the plugin :)

**Comment by tweecool** [comment]
Hi.
I tried to purchase a plan but not working.
On 22 Oct 2015 11:42, skiokko notifications@github.com wrote:Some small support to author is nothing for this great plugin.

**Comment by skiokko** [comment]
Also for me not work. Was too good for be true. I know for min 100$/year.
From my side I can support 20/25$,
Guys come one some support and put again live this work!

**Comment by tweecool** [comment]
Hi, I will put it back up ...please wait...I am just too busy...1and1 let me down at a very bad time. And thank you for your offer!
On 22 Oct 2015 13:45, skiokko notifications@github.com wrote:Also for me not work. Was too good for be true. I know for min 100$/year.
From my side I can support 20/25$,
Guys come one some support and put again live this work!

**Comment by NitroxydeX** [comment]
Nice to hear that Tweecool will be up soon.

And yeah. This is the 1&1 I know from Germany. Not really good support over there.

**Comment by polonel** [comment]
If you can publish the backend API thats sending back to the plugin. I am willing to put it into my VPS cluster. This is a great plugin, that makes integrating tweets very simple. I just haven't sat down and recreated the API service you did to talk to your plugin, mainly because why recreate something that has worked so well.

**Comment by tweecool** [comment]
Hey,
It's up and running, expect some downtime due to migration.
Laters
On 22 Oct 2015 13:45, skiokko notifications@github.com wrote:Also for me not work. Was too good for be true. I know for min 100$/year.
From my side I can support 20/25$,
Guys come one some support and put again live this work!

**Comment by tweecool** [comment]
Hey,
It's up and running, expect some downtime due to migration.
Laters
On 22 Oct 2015 11:30, Rafael Díez notifications@github.com wrote:Hi, check this VPS: http://www.servermom.org/boltvm-promo/2490/  ==>
20$/year.
It's better than a shared hosting but not very expensive.

2015-10-22 12:28 GMT+02:00 skiokko notifications@github.com:

> Thanks for answer! Understood, I also tried years ago a free service but
> revenue of ADS was zero. Only goodway I found to make money is to publish
> plugins on http://codecanyon.net/
> Good luck.
> Federico
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tweecool/tweecool-jquery-plugin/issues/2#issuecomment-150173788
> .

## 

_Rafael Díez_
email: rdiezv@gmail.com
twitter: @rdiezv https://twitter.com/rdiezv
web: www.rafaeldiez.com

**Comment by skiokko** [comment]
Great news! Tell me paypal email for donation.

**Comment by tweecool** [comment]
Hi Skiokko,

There is a donate button on http://tweecool.com/ just below the navigation.
A small contribution will be enough and thank you in advanced!

> On 27 October 2015 at 13:23 skiokko notifications@github.com wrote:
> 
>  Great news! Tell me paypal email for donation.
> 
>  —
>  Reply to this email directly or view it on GitHub
> https://github.com/tweecool/tweecool-jquery-plugin/issues/2#issuecomment-151492604
> .

{ TweeCool Team 2k15 }

**Comment by tweecool** [comment]
Hey Skiokko,

not sure if you received my email, in case you haven't. I'd like say thank you so much, I received it!

**Comment by skiokko** [comment]
Hi,
Thank you for confirmation :). Your work is very good, a support is the
minimum :)
Bye,
Federico

[image: PIXOR | FEDERICO SCHIOCCHET] PIXOR | Federico Schiocchet | Web
Developer
WWW.PIXOR.IT http://www.pixor.it/[image: linkedin]
https://it.linkedin.com/pub/federico-schiocchet/32/a90/114 [image: skype]
https://www.facebook.com/mypixor [image: skype]
https://twitter.com/_pixor [image: skype]
https://www.youtube.com/c/PixorIt [image: skype]
https://www.google.com/+PixorIt

2015-11-07 19:19 GMT+01:00 tweecool notifications@github.com:

**Comment by shahilmhd** [comment]
Is the API down right now ? Its shows No tweets available since 1 hour.

**Comment by vishalbaruah** [comment]
the api not working and is showing cross domain problems...it was working well 2days ago...ryt now its not working
