### ISSUE TITLE
Server Down

### ISSUE THREAD

**Issue by smanny** [tweecool/tweecool-jquery-plugin#4]
Is the server for https://www.api.tweecool.com down? The script uses this URL to return a JSON response of tweet data, but it seems to be timing out. Perhaps there is a way to incorporate a direct connection to the Twitter API and then format the response from that?

**Comment by tweecool** [comment]
Hi Stuart, 
Should be back to normal now. Few things have changed please check the site and get the new js files. 
Thanks. 
On 3 Jun 2016 1:59 pm, Stuart Manny notifications@github.com wrote:Is the server for https://www.api.tweecool.com down? The script uses this URL to return a JSON response, but it seems to be timing out.

**Comment by smanny** [comment]
The updates JS file seems to have did the trick. The responses are back from the server. I appreciate the quick response.

**Comment by smanny** [comment]
For a moment the script returned a response. Now I receive another error related to "Access Control Origin" being null. Any ideas? My side of things?
![capture](https://cloud.githubusercontent.com/assets/7737516/15824415/b3c3d1a2-2bc4-11e6-8230-a25d7553bc80.PNG)

Headers:

GET /api/?screenname=XXXXXXXX&count=3 HTTP/1.1
Host: tweecool.com
Connection: keep-alive
Cache-Control: max-age=0
Accept: application/json, text/javascript, _/_; q=0.01
Origin: **null**
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8

**Comment by smanny** [comment]
Strangely the above origin error seemed to resolve after a few minutes and trying again. I will close this issue as things are fully functioning.

**Comment by smanny** [comment]
Can we use HTTPS for the endpoint?

**Comment by smanny** [comment]
Any update on this? My site uses HTTPS. Can this plugin be updated to support that?

**Comment by tweecool** [comment]
TweeCool CMS should handle HTTPS . Please check our website http://tweecool.com/
