### ISSUE TITLE
No Tweets Available

### ISSUE THREAD

**Issue by shahilmhd** [tweecool/tweecool-jquery-plugin#5]
The plugin is throwing the error saying no tweets available since 1 hour. is the server down ?

**Comment by shahilmhd** [comment]
XMLHttpRequest cannot load http://tweecool.com/api/?screenname=dsw&count=1. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 404.

**Comment by tweecool** [comment]
Please check http://tweecool.com/ for updates
